package ca.mcgill.ecse223.resto.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;

import javax.swing.JFrame;
import javax.swing.JLabel;

import acm.graphics.GObject;
import ca.mcgill.ecse223.resto.controller.Controller;
import ca.mcgill.ecse223.resto.controller.InvalidInputException;
import ca.mcgill.ecse223.resto.model.Table;

public class MoveTableUI extends javax.swing.JFrame {

    /**
     * Creates new form MoveTableUI
     */
    public MoveTableUI(Table t) {
    	selectedTable = t;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        selectedTableLabel = new javax.swing.JLabel();
        moveTableLabel = new javax.swing.JLabel();
        selecetdTableLabel = new javax.swing.JLabel();
        currentXLabel = new javax.swing.JLabel();
        currentYLabel = new javax.swing.JLabel();
        tableNum = new javax.swing.JLabel();
        currentX = new javax.swing.JLabel();
        currentY = new javax.swing.JLabel();
        newXLabel = new javax.swing.JLabel();
        newYLabel = new javax.swing.JLabel();
        xTextField = new javax.swing.JTextField();
        Ytextfield = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        selectedTableLabel.setText("Selected Table");

        moveTableLabel.setText("Move table ");

        selecetdTableLabel.setText("Selected Table:");

        currentXLabel.setText("current x:");

        currentYLabel.setText("current y:");

        tableNum.setText(String.valueOf(selectedTable.getNumber()));

        currentX.setText(String.valueOf(selectedTable.getX()));

        currentY.setText(String.valueOf(selectedTable.getY()));

        newXLabel.setText("new x:");

        newYLabel.setText("new y:");

        xTextField.setText("new int");

        Ytextfield.setText("new int");

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selecetdTableLabel)
                    .addComponent(currentXLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(currentYLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newYLabel)
                            .addComponent(newXLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tableNum)
                        .addComponent(currentX))
                    .addComponent(currentY, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(selectedTableLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(moveTableLabel)
                                .addGap(0, 51, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ytextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(UpdateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(selectedTableLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecetdTableLabel)
                    .addComponent(tableNum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentXLabel)
                    .addComponent(currentX))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentYLabel)
                    .addComponent(currentY))
                .addGap(37, 37, 37)
                .addComponent(moveTableLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newXLabel)
                    .addComponent(xTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newYLabel)
                    .addComponent(Ytextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateButton)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setVisible(true);
    }// </editor-fold>                        

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	// call the controller
    	try {
    		Controller.moveTable(selectedTable, Integer.parseInt(xTextField.getText()), Integer.parseInt(Ytextfield.getText()));
			GLabeledRect newTable = new GLabeledRect(Integer.parseInt(xTextField.getText()), Integer.parseInt(Ytextfield.getText()), selectedTable.getWidth(), selectedTable.getLength(), selectedTable.getNumber());
			newTable.setColor(Color.GREEN);
			DragCanvas.labeledRects.add(newTable);
			RestoAppUI.jScrollPane1.add(newTable);
			for(GLabeledRect r: RestoAppUI.jScrollPane1.labeledRects){
				 if(r.getTableNum() == selectedTable.getNumber()){
					 //System.out.println("table number = "+table.getNumber());
					 RestoAppUI.jScrollPane1.labeledRects.remove(r);
					 RestoAppUI.jScrollPane1.remove(r);
				 }
			 }
			
    	} catch (InvalidInputException e) {
    		createErrorFrame(e.getMessage());
    	}
    	//TODO refresh data on the dragable panel
    }       
    
    private void createErrorFrame(String error){
		JFrame errorFrame = new JFrame();
		errorFrame.setMinimumSize(new Dimension(300, 100));
		errorFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		JLabel succesLabel = new JLabel("Error: ");
		JLabel newInfo = new JLabel(error);
		GridLayout layout = new GridLayout(2,1);
		errorFrame.setLayout(layout);
		errorFrame.add(succesLabel);
		errorFrame.add(newInfo);

		errorFrame.setVisible(true);
		
    }

    

    // Variables declaration - do not modify                     
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField Ytextfield;
    private javax.swing.JLabel currentX;
    private javax.swing.JLabel currentXLabel;
    private javax.swing.JLabel currentY;
    private javax.swing.JLabel currentYLabel;
    private javax.swing.JLabel moveTableLabel;
    private javax.swing.JLabel newXLabel;
    private javax.swing.JLabel newYLabel;
    private javax.swing.JLabel selecetdTableLabel;
    private javax.swing.JLabel selectedTableLabel;
    private javax.swing.JLabel tableNum;
    private javax.swing.JTextField xTextField;
    private Table selectedTable;
    // End of variables declaration                   
}
