package ca.mcgill.ecse223.resto.view;

import java.awt.Dimension;
import java.awt.GridLayout;

import javax.swing.JFrame;
import javax.swing.JLabel;

import ca.mcgill.ecse223.resto.controller.Controller;
import ca.mcgill.ecse223.resto.controller.InvalidInputException;
import ca.mcgill.ecse223.resto.model.OrderItem;
import ca.mcgill.ecse223.resto.model.Table;

import java.util.List;

public class ViewOrderFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewOrderFrame
     */
    public ViewOrderFrame(Table aTable) {
        table = aTable;
      //try to get a list of OrderItems
    	try{
    		items = Controller.getOrderItems(table);
    		initComponents(items);
    	}catch(InvalidInputException e){
    		 createErrorFrame(e.getMessage());
    	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "serial" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(List<OrderItem> items) {
    	
        orderLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        orderLabel.setText("Order");

        jLabel2.setText("at Table #");

        jLabel3.setText(String.valueOf(table.getNumber()));
        
        if(items.size() < 1){
        	//No order items for s given order yet, initilize the table empty
        	 jTable1.setModel(new javax.swing.table.DefaultTableModel(
        	            new Object [][] {
        	                {null, null},
        	                {null, null},
        	                {null, null},
        	                {null, null},
        	                {null, null},
        	                {null, null}
        	            },
        	            new String [] {
        	                "Dish", "Quantity"
        	            }
        	        ) {
        	            Class[] types = new Class [] {
        	                java.lang.String.class, java.lang.Integer.class
        	            };

        	            public Class getColumnClass(int columnIndex) {
        	                return types [columnIndex];
        	            }
        	        });
        }else{
        	//place the order items in the table
        	Object[][] data = new Object[items.size()][2];
        	int x = 0;
        	
        	for(OrderItem i : items){
        		data[x][0] = i.getPricedMenuItem().getMenuItem().getName();
        		data[x][1] = 1;
        		x++;
        	}
        	
        	 jTable1.setModel(new javax.swing.table.DefaultTableModel(
     	            data,
     	            new String [] {
     	                "Dish", "Quantity"
     	            }
     	        ) {
     	            Class[] types = new Class [] {
     	                java.lang.String.class, java.lang.Integer.class
     	            };

     	            public Class getColumnClass(int columnIndex) {
     	                return types [columnIndex];
     	            }
     	        });
        }
       
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(orderLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(136, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(orderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
        );

        pack();
        setVisible(true);
    }// </editor-fold>                        
    
    private void createErrorFrame(String error){
		JFrame errorFrame = new JFrame();
		errorFrame.setMinimumSize(new Dimension(300, 100));
		errorFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		JLabel succesLabel = new JLabel("Error: ");
		JLabel newInfo = new JLabel(error);
		GridLayout layout = new GridLayout(2,1);
		errorFrame.setLayout(layout);
		errorFrame.add(succesLabel);
		errorFrame.add(newInfo);

		errorFrame.setVisible(true);
		
	}

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel orderLabel;
    private Table table;
    private List<OrderItem> items;
    // End of variables declaration                   
}
